const songs = [
  "Nataša Matić - Šampanjac - (Audio 2012)",
  "KISMI-MILIONERCE",
  "Koki Burdalic - ARMANI",
  "Kemal Malovcic Ameriko Cemeriko",
  "Bora Drljaca - Ja sam snajder - (Audio 1999)",
  "Bora Drljaca - Stari vuk - (Audio 2004)",
  "Bora Drljaca Prijo Moja Kako Ćemo",
  "Stevo Damljanovic Garo - Da Si Sa Mnom Jela Zutu Proju",
  "Erotski Hitovi-Cika postar",
  "Mica Trofrtaljka - Rdjavome kupcu i dlake smetaju",
  "Slobodan Mulina - Igrale se delije",
  "Boja vasic sav Baro. NOVO 2012",
  "Hittttt Branko Amzic Novo Dik O Branko Barvalo 2014",
  "Branko Amzic Dijamanti Novo 2014",
  "Erdjan & Manuel Ork. Facebook - But Sigate Saljubingjuma - Exxplosivno Hit 2016 by Studio Jackica",
  "Julija Bikova - Samo tut mangava by Seat Berisha",
  "Sunaj - Mi Familija Number One - 2016 █▬█ █ ▀█▀",
  "SORINA-BESAV TELE.",
  "Zlata Petrovic - Aj vino vino",
  "Zlata Petrovic - Madjije",
  "Snezana Jovanovic Sikica - Zavede me momak los",
  "Zlata Petrovic - 'Ej take take ta - (Audio 1995)",
  "Ljilja Bela - Djido - (Audio 2002)",
  "Zorica Markovic - Vlaska svadba - (Audio 2006)",
  "MARINA DALIPOVIC - MAHERKA - (OFFICIAL VIDEO) 2020. NOVO",
  "Tomislav Colovic - Mali mrav",
  "Ćana - Ima, Ima Stila",
  "MARINA DALIPOVIC 2013 ALAL VERA",
  "Marina Dalipovic Vadi vadi pare",
  "Marina Dalipovic - Bankomat (Official 2018)HD",
  "Sani Radelić// Pronašla si čujem nekog//OFFICIAL MUSIC VIDEO 2014",
  "Vino mândro (Cover) - Drăghici Ionel şi formația BRAVO",
  "Ljuta I Slatka",
  "Zoran Jagodić - Dadule, Nanule BOGTEJEBO",
  "Moj Ford stari",
  "Mahala Rai Banda - Mahalageasca",
  "Hepi brdej 2 juuu",
  "Boza Nikolic Bidai",
  "ECI PECI PEC-IGGYXspecijal za 30K subscribera",
  "Marko Pantic Maki - Mobitel",
  "Coki i centa",
  "Комбайна-вършачка",
  "Ljepi San - Treba znati Zenu Udarati (Uzivo KOLO)",
  "Mensur Duric - Duni lampu",
  "Petrica Mitu Stoian - Ma culcai la cap de punte",
  "Svetozar Lazovic Gongo - Topic Svelovo kolo",
  "Cowboy Lely MARKO",
  "עומר אדם - הופה",
  "Mirsada i Jarani - Udri zajko",
  "Pauk kolo sasa nikolic",
  "Vesna Centa Zelena Salata",
  "Twins - Crvenkapa",
  "Cunami Bend - Sampion (Official Cover 2019)HD",
  "MAKI FRAJERI ♫ █▬█ █ ▀█▀♫ ©2017",
  "Damir Horvat - Mix 2021",
  "Beki Bekic - Tri kuce u tri reda - (Audio 2013) HD",
  "Boba 2004 - Svadba Od Milion Evra",
  "Đinđi Rinđi 100%",
  "Šljivovica Zoran Jagodic Rule",
  "Zoran Vanev - Tanga - (Audio 2007)",
  "Fazlija - 2004 - 05 - Ciganska svadba",
  "Fazlija - Za Dusmane",
  "Dzej Ramadanovski - Lubenica",
  "Zekija Husetovic - Sandzak Bosna",
  "Techno - Gospodi pomiluj (Remix) ♫ KVP Production",
  "Acko Nezirovic - Maco",
  "BENNY SARBU | RAUL STEFONI DRAJF 2022 Specterr 720p",
  "milan dimic i bobi cergar opsanoo drajffffff",
  "Ivan Francuz Kradljivac",
  "Branko Amzic SOSE SINE",
  "Branko amzic sa svojem majkom.avi",
  "Thank You USA - Armend Miftari MENDI (Official Video)",
  "Kibori - Mahala Rai Banda",
  "Goran Bregović - Gas gas - (audio) - 2007",
  "Keba - Ovo srce",
  "Kemal (KM) Malovcic - Tek tek",
  "Fazlija - Sipaj care - 2009.wmv",
  "MILKO KALAYDZHIEV FT. LONG G - PROFESOR",
  "MILKO KALAYDZHIEV & NASKO MENTATA - BRAMCHALKA",
  "MILKO KALAYDZHIEV & NASKO MENTATA - GAZ",
  "Veselje kod Alberta & Sanele Orkestar Alexa Cergara",
  "Drajf-Kolo Uzivo 2010 Miki Cortan i Dusko Gurbet",
  "CENTA Bonbonice, karamelice",
  "Boro Majstorovic Kawasaki",
  "Boro Majstorovic Dodji Dragana",
  "Marko Pantic Maki - Mobitel",
  "Mirsad Rizvic Kad se budes udala",
  "Travolta Iz Borče Grede- Hej Travolta",
  "Sandokan'Mc-Daj bombu(Official video)",
  "Drag",
  "Dragan Ćirkovic Ćira peva Šaban Šaulić - Samo neka Ćira svira - Gold Music - ( 2007 )",
  "Šaban Bajramović - Opa Cupa",
  "Grófo Remegős pergető Durva.wmv",
  "grofo-brutál",
  "Tibor Universalu' - Am plecat prin tari straine",
  "Nicusor de la Alba - Sa cante muzica [videoclip oficial]",
  "Bobby Rostas - Norocu' si omenia [videoclip oficial]",
  "Nicolae Guta & Sorina - Nunta",
  "Sandu Ciorba - Ia d-aici ca n-ai servici",
  "Eugen Casanova - Nelson Mondialu [VIDEOCLIP NOU]",
  "Fazlija x 50 Cent - Malo Viski Malo Coca Cola",
  "Rade Jorovic - Zene vole oficire - (Official Video)",
  "Gypsy Phonk",
  "Georges Bodossian Balkanmania",
  '[架空軍歌]豊敷讃連邦海軍 行進曲 "푸른 물결(Blue wave)" with 重音テト',
  "Säkkijärven polkka",
  "Snezana Savic - Tri poljupca za srecu",
  "MIRJANA - Dražen Stjepandić",
  "[YT2mp3.info] - Dodji Švabo da vidiš - English Lyrics (320kbps)",
  "Ajnur Serbezovski - Kokain - Sezam produkcija (Tv Sezam 2021)",
  'Prelepi Miške i Orkestar "Šećeri" - Aljaska',
  "Almir Gio Antic AGA - Boom, boom - Sezam produkcija (Tv Sezam 2021)",
  "Barabe bend  Tastina igra  Sezam produkcija Tv Sezam 2021",
  "BONI MIX █▬█ █ ▀█▀♛ 1999 _ Огън И Лед - Готин - Звезда BG - MUSIC STEREO 432 HZ",
  "Boža Nikolić - Acvaba prala - (audio) - 1998 Grand Production",
  "Boža Nikolić - Didala - (audio) - 1998 Grand Production",
  "BRANKO AMZIC  NOVO NOVO",
  "Denis Ramic Jackson - Srecna svadba - Sezam produkcija (Tv Sezam 2021)",
  "Djani  Tutifruti  Audio 2000",
  "Dobrivoje Topalović - Imali smo bašču šljiva - (Audio 2002)",
  "Dragan Centa & Orkestar Tigrovi -Show- 2013 Exclusive By Doni V.I.P",
  "Drajf- Kolo Uzivo 2016 Benny Sârbu i Raul Stefoni Drugi Deo 2 Reupload",
  "Dzej Ramadanovski  Lubenica  Audio 1991",
  "Ersan & DJ BUKUrije - Tallava Hit  Katy Perry",
  "Franc Ferrari - Nikom nije kao nama - Sezam produkcija (Tv Sezam 2019)",
  "7Grofo joreggelt joreggelt (bekokainozva)",
  "Markisa Kozic Maky - Natenane - Sezam produkcija (Tv Sezam 2021)",
  "MILKO KALAYDZHIEV - GSM - МИЛКО КАЛАЙДЖИЕВ - GSM",
  "Milos Bojanic - Cigra - (Audio 2006)",
  "MIRA & MILKO KALAYDZHIEV - HEY MALKATA - МИРА И МИЛКО КАЛАЙДЖИЕВ - ХЕЙ МАЛКАТА",
  "Nicolae Guta nou -  Trifoi - Joc Tiganesc - fa muiere taitei si Mamaliga",
  "Play Boy Alen Ademović",
  "Ramo Legenda - Gara - (Audio 2000)HD",
  "Ranko Amadeus - Oklopno Rave Kolo Gucha 2001 GTLX - (Audio 1996)",
  "Safet Sabanovic Sabi - Terno daje kamerav - Sezam produkcija (Tv Sezam 2021)",
  "Sejo Kalac - Tika tak - (Audio 2003)",
  "super ciganskaacalari bomba",
  "Valentina Raicu - Miki Cortan i Vojkan 2009 MiXxXXxX 1",
  "Miki Cortan -Vojkan Drajf i Violeta Lumina 2006",
  "Violeta Sandala by BuKa",
  "Zlata Petrovic - Madjije - ( Audio 1994 ) HD",
  "Zorica Markovic  Crni milioner  Audio 2003 HD",
  "Бони - Звезда 1999   Onkyo Player HD",
  "Ciganska pesma MIU MIU",
  "Jasmin Jusic - Dzek Pot",
  "Sandu Ciorba - Pe cimpoi",
  "Sorina - Ciupi Ciupi",
];

exports.songs = songs;
